export {
  INSTANCE_GRAPH_VERSION,
  INSTANCE_NODE_KIND,
  INSTANCE_OCCURRENCE_ID_PREFIX,
  emptyInstanceGraph,
  normalizeInstanceGraph,
  hasInstanceGraph,
  isInstanceNode,
  instanceDefinition,
  resolveInstanceNode,
  instanceOccurrenceId,
  isInstanceOccurrenceId,
  parseInstanceOccurrenceId,
  resolveInstanceOccurrence,
  projectInstanceOccurrenceSubtree,
  updateInstanceOccurrenceRoot,
  instanceOccurrenceWorldContext,
  compactHierarchyRoots,
  compactSceneToInstanceGraph,
  duplicateReferenceRoots,
  replaceInstanceObjectDefinition,
  replaceInstanceOccurrenceObjectDefinition,
  assemblyChildrenForInstance,
  ungroupAssemblyInstance,
  projectInstanceGraphObject,
  projectInstanceGraphRoot,
  projectInstanceGraphScene,
  projectInstanceGraphChanges,
  validateInstanceGraph,
  instanceGraphDiagnostics,
  instanceGraphCompiledProjectionDiagnostics
} from "./InstanceGraph.js";

export { InstanceGraphProjectionCache } from "./InstanceGraphProjectionCache.js?build=20260808-0053f";
